first iteration kinda

diff --git a/ext2btrfs b/ext2btrfs
--- a/ext2btrfs
+++ b/ext2btrfs
@@ -1,112 +1,77 @@
 #! /usr/bin/env bash
-# scp ext2btrfs root@12.345.678.912: && ssh root@12.345.678.912 bash ext2btrfs
 
-set -e
+set -e $@
 
 RECOVERY="${RECOVERY:-}"
 REBOOT="${REBOOT:-}"
+INIT_OPTS="${INIT_OPTS:-}"
 
-#apt-get update
-apt-get install -y btrfs-progs
-apt-get install -y busybox-static
+# systemd -> /usr/lib/systemd/systemd
+abs() { # name
+  readlink -f "$(which "$1" || echo 1>&2 "$1 not available in PATH!")"
+}
+
+move_prog() { # name
+  prog="$(abs "$1")"
+  cp -v "$prog" "/mnt/bin/" 1>&2
+  for f in $(ldd "$prog" | perl -ne '/(\/\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
+    [ -n "$2" ] && echo "/mnt/${f%/*}"
+    [ -f "/mnt/$f" -o ! -f "$f" ] && continue
+    mkdir -p "/mnt/${f%/*}"
+    cp -L "$f" "/mnt/$f"
+  done
+}
+
+wrap() {
+  libs="$(move_prog "$1" 1 | sort -u | tr '\n' ':')"
+  name="$(basename "$1")"
+  tgt="/mnt/bin/$name-wrapper"
+  cat > "$tgt" <<EOF
+#!/bin/sh
+LD_LIBRARY_PATH="$libs" exec "/mnt/bin/$name" \$@
+EOF
+  chmod +x "$tgt"
+  [ -n "$2" ] && echo "$tgt"
+}
+
+echo "=== installing packages ==="
+
+pkgs() {
+  apt-get install -y btrfs-progs busybox-static
+}
+pkgs || { apt-get update; pkgs; }
+
+echo "=== building temporary root ==="
 
 mount -t tmpfs ramdisk /mnt
-
 mkdir /mnt/{old,proc,sys,dev,run}
-
 mkdir -p /mnt/{bin,sbin,usr/bin,usr/sbin}
 
-busybox="$(which busybox)"
+linker="$(ldd "$(which cat)" | grep "ld-linux" | awk '{ print $1 }')"
+echo "Detected dynamic linker $linker"
+cp -Lr "${linker%/*}" "/mnt${linker%/*}"
+# don't assume symlinks, just bind mount
+mount --bind "/mnt${linker%/*}" "${linker%/*}"
+
+busybox="$(abs busybox)"
 cp "$busybox" /mnt/bin
 /mnt/bin/busybox --install /mnt/bin
 
-btrfsconvert="$(which btrfs-convert)"
-cp "$btrfsconvert" /mnt/sbin
-for f in $(ldd "$btrfsconvert" | perl -ne '/(\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
-  [[ ! -f $f ]] && continue
-  mkdir -p /mnt/${f%/*} && cp -v $f /mnt/$f
-done
-
-btrfs="$(which btrfs)"
-cp "$btrfs" /mnt/sbin
-for f in $(ldd "$btrfs" | perl -ne '/(\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
-  [[ ! -f $f ]] && continue
-  mkdir -p /mnt/${f%/*} && cp -v $f /mnt/$f
-done
-
-strace="$(which strace)"
-cp "$strace" /mnt/sbin
-for f in $(ldd "$strace" | perl -ne '/(\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
-  [[ ! -f $f ]] && continue
-  mkdir -p /mnt/${f%/*} && cp -v $f /mnt/$f
-done
-
-e2fsck="$(which e2fsck)"
-cp "$e2fsck" /mnt/sbin
-for f in $(ldd "$e2fsck" | perl -ne '/(\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
-  [[ ! -f $f ]] && continue
-  mkdir -p /mnt/${f%/*} && cp -v $f /mnt/$f
-done
-
-umount="$(which umount)"
-cp "$umount" /mnt/sbin
-for f in $(ldd "$umount" | perl -ne '/(\S+) \(0x[a-z0-9]+\)/ and print "$1\n"'); do
-  [[ ! -f $f ]] && continue
-  mkdir -p /mnt/${f%/*} && cp -v $f /mnt/$f
-done
-
-#cat > /mnt/init <<'EOF'
-##!/bin/bash
-#
-#run_from_file() {
-#  local f t
-#  for f in /dev/fd/*; do
-#    [ -h $f ] || continue
-#    [ $f -ef "$0" ] && return
-#  done
-#  t=$(mktemp)
-#  cat > $t
-#  if [ "$(head -n 1 $t)" = '#!/bin/bash' ]; then
-#    chmod +x $t
-#    exec /bin/bash $t "$@" </dev/fd/2
-#  else
-#    rm -f $t
-#    echo "Direct execution not supported with this shell ($_)." >&2
-#    echo "Please try bash instead." >&2
-#    exit 1
-#  fi
-#}
-#
-## do not modify the two lines below
-#[ -h /dev/fd/0 ] && run_from_file
-##!/bin/bash
-#echo "=== starting init ==="
-#set -x
-#/bin/bash -l -i
-#set +x
-#echo "=== end of init. rebooting in 5s ==="
-#sleep 5
-#reboot -f
-#EOF
-
-#cat > /mnt/init <<'EOF'
-##!/bin/bash
-#echo "=== starting init ==="
-#set -x
-#/bin/bash -l -i
-#set +x
-#echo "=== end of init. rebooting in 5s ==="
-#sleep 5
-#reboot -f
-#EOF
+move_prog btrfs
+move_prog btrfs-convert
+move_prog e2fsck
+move_prog strace
+move_prog lsof
+move_prog fuser
 
 root="$(findmnt / --first-only --noheadings -o SOURCE)"
 root_dev="$(echo "$root" | sed 's/[0-9]\+$//')"
+echo "Discovered root dev: $root_dev"
 
 cat > /mnt/init <<EOF
 #!/bin/sh
 
-set -e
+set -e $INIT_OPTS
 
 root="$root"
 root_dev="$root_dev"
@@ -137,11 +102,14 @@ on_exit() {
 trap on_exit EXIT
 
 echo "=== unmounting old root ==="
+mount --move /old/proc /proc
+mount --move /old/sys /sys
+mount --move /old/dev /dev
+mount --move /old/run /run
+fuser -SIGKILL --verbose --kill --mount /old
 umount -l "$root"
-timeout 5s sh -c "until mount '$root' /old; do sleep 1; done"
-timeout 5s sh -c "until umount '$root'; do sleep 1; done"
-
-echo "=== starting init ==="
+# basically open($root, O_RDONLY | O_EXCL) with extra steps
+timeout 10s sh -c "while e2fsck -E journal_only -n '$root' 2>&1 | grep 'is in use' > /dev/null; do sleep 1; done"
 
 echo "=== converting to btrfs ==="
 /sbin/btrfs-convert -L "$root"
@@ -185,19 +153,62 @@ EOF
 
 chmod 0755 /mnt/init
 
+echo "=== evicting systemd ==="
+
+path="$(find /proc/1/fd -type l | xargs -n1 readlink | grep "systemd-executor" || true)"
+if [ -z "$path" ]; then
+  echo "Couldn't find systemd-executor!"
+  exit 1
+fi
+wrapper="$(wrap "$path" 1)"
+mv "$(readlink -f "$path")" /systemd-executor
+rm -f "$path"
+ln -s "$wrapper" "$path"
+
+wrapper="$(wrap systemd 1)"
+sysd="$(abs systemd)"
+mv $sysd /systemd
+ln -s "$wrapper" $sysd
+
+systemctl daemon-reexec
+
+if find /proc/1/maps -type l \
+    | xargs -n1 readlink \
+    | xargs -n1 findmnt --nohead -o TARGET -T \
+    | grep "^/$"; then
+  echo "Couldn't evict systemd! Some files are still mapped from the root."
+  echo "Contents of /proc/1/maps:"
+  cat /proc/1/maps
+  exit 1
+fi
+
+if find /proc/1/fd -type l \
+    | xargs -n1 readlink \
+    | xargs -n1 findmnt --nohead -o TARGET -T \
+    | grep "^/$"; then
+  echo "Couldn't evict systemd! Some files is still open on the root."
+  echo "Contents of /proc/1/fd:"
+  ls -l /proc/1/fd
+  exit 1
+fi
+
+echo "=== stopping all units ==="
+
+preserve="cloud-init|tty|journald"
+
+systemctl list-units --type=socket --plain --no-legend \
+  | cat | awk '{ print $1 }' >> /sysd-state
+systemctl list-units --type=service --state=running --plain --no-legend \
+  | cat | awk '{ print $1 }' > /sysd-state
+systemctl list-units --type=socket --plain --no-legend \
+  | cat | grep -Ev "$preserve"| awk '{ print $1 }' | xargs systemctl stop
+systemctl list-units --type=service --state=running --plain --no-legend \
+  | cat | grep -Ev "$preserve" | awk '{ print $1 }' | xargs -t systemctl stop
+
+echo "=== switching root ==="
+
 losetup -D || true
 modprobe btrfs
-
-sleep 1
-trap - EXIT
-
-mount --types proc /proc /mnt/proc
-mount --rbind /sys /mnt/sys
-mount --make-rslave /mnt/sys
-mount --rbind /dev /mnt/dev
-mount --make-rslave /mnt/dev
-mount --bind /run /mnt/run
-mount --make-slave /mnt/run
 
 # pivot_root won't work with MS_SHARED
 mount --make-private /
